### ISSUE TITLE
When I play next?

### ISSUE THREAD

**Issue by brunoraljic** [doboj-labs/pes-bot-api#1]
> @pes-botina next me
should return something like
> @your.name play in 2 match(es) against @your.opponent

While here, command `next match` should be refactored to `next`

**Comment by ognjetina** [comment]
I think we should not tag the opponent (spamming for no good reason).

**Comment by brunoraljic** [comment]
I thought about that for a second as well, but it is also a bit helpful or a reminder for the opponent. 
First version doesn't have to mention anyone.

**Comment by brunoraljic** [comment]
Implemented
@pes-botina my turn returns appropriate info
